
# SEO settings
title: "John Patterson"
description: "Personal profile of John Patterson, software engineer."
keywords: "john, patterson, john patterson, programming, programmer, software, engineer, mathematics"
url: http://johnppatterson.com # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/john-patterson/john-patterson.github.io
twitter_username: "AcadianCoder"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "John P. Patterson"
  job      : "Software Engineer"
  bio      : "Forgetfulness is the path to enlightenment."
  thumb    : /images/author.jpg
  email    : john@johnppatterson.com
  url      : https://johnppatterson.com
  github   : http://github.com/john-patterson
  twitter  : http://twitter.com/AcadianCoder
  linkedin : http://linkedin.com/in/john-patterson

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@AcadianCoder"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
