# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Patterson
email: john@johnppatterson.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of John Patterson, programmer at large.
baseurl: "" # the subpath of your site, e.g. /blog
url: "127.0.0.1:4000" #"http://johnppatterson.com" # the base hostname & protocol for your site
twitter_username: AcadianCoder
github_username:  john-patterson

# Build settings
markdown: kramdown
